FROM dpage/pgadmin4:latest

# Rótulos de documentação
LABEL name="cxa/pgadmin4" \
    maintainer="Antonio Jousivan <ajssti@gmail.com>" \
    summary="Imagem para execução pgadmin4." \
    description="sudo docker run --name <NOME_CONTAINER> --hostname <NOME_CONTAINER> -d -e <VARIAVEL>=<VALOR_VARIAVEL>" \
    PGADMIN_DEFAULT_EMAIL="pgadmin" \
    PGADMIN_DEFAULT_PASSWORD="pgadmin"



EXPOSE 80 443

